version: '2.2'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: database
    image: postgres:13
    environment:
        POSGRES_USER: 'postgres'
        POSGRES_PASSWORD: '6Yr!baH(9nDt'
        POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/posgresql/data/

  django:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command:  bash -c "python ~/restapi/manage.py migrate &&
              python ~/restapi/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/

  vue:
    container_name: frontend
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    depends_on:
      - django
  
  