version: '2.12'

services:
  vue:
    container_name: vue3-GZExport
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'