# Generated by Django 4.1.3 on 2022-11-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('date_deal', models.DateField()),
                ('tool', models.CharField(max_length=255)),
                ('delivery_start', models.DateField()),
                ('delivery_end', models.DateField()),
                ('volume', models.FloatField()),
                ('cost', models.FloatField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.counterparty')),
                ('delivery_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.deliverypoint')),
            ],
        ),
    ]
