# Generated by Django 4.1.3 on 2022-11-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('date_deal', models.DateField()),
                ('delivery_start', models.DateField()),
                ('delivery_end', models.DateField()),
                ('volume', models.FloatField()),
                ('cost', models.FloatField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.counterparty')),
                ('delivery_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.deliverypoint')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Deals',
        ),
        migrations.AddField(
            model_name='deal',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tool'),
        ),
    ]
