# Generated by Django 4.1.3 on 2022-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_type_alter_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='cost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
