# Generated by Django 4.1.3 on 2022-11-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deal_cost_alter_deal_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='volume',
            field=models.FloatField(),
        ),
    ]
