# Generated by Django 4.1.3 on 2022-11-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_deal_cost_alter_deal_volume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.CharField(max_length=10)),
                ("volume", models.FloatField(null=True)),
                ("cost", models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="deliverypoint",
            old_name="point_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tool",
            old_name="tool_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="type",
            old_name="type_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="counterparty",
            name="cp_name",
        ),
        migrations.AddField(
            model_name="counterparty",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counterparty",
            name="score",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="counterparty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.counterparty",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="delivery_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deliverypoint",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="tool",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.tool"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.type"
            ),
        ),
    ]
