# Generated by Django 4.1.3 on 2022-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_deal_cost_alter_deal_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
