# Generated by Django 4.1.3 on 2022-11-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_counterparty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterparty',
            old_name='cp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deliverypoint',
            old_name='point_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='tool_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
