# Generated by Django 4.1.3 on 2022-11-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_report_rename_point_name_deliverypoint_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
