# Generated by Django 4.1.3 on 2022-11-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_counterparty_name_alter_deliverypoint_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="counterparty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.counterparty",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="delivery_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.deliverypoint",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="tool",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.tool"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.type"
            ),
        ),
    ]
