# Generated by Django 4.1.3 on 2022-11-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_deal_counterparty_alter_deal_delivery_point_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="deliverypoint",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
